
/*
 * @(#)CommitmentStore.java
 *
 * Generated by <a href="http://lci.cs.ubbcluj.ro/ocle/>OCLE 2.0</a>
 * using <a href="http://jakarta.apache.org/velocity/">
 * Velocity Template Engine 1.3rc1</a>
 */
import java.util.LinkedHashSet;
import java.util.Set;

/**
 *
 * @author unascribed
 */
public class CommitmentStore {

    
    public final Set getInference() {

        if (inference == null) {
            return java.util.Collections.EMPTY_SET;
        }
        return java.util.Collections.unmodifiableSet(inference);
    }
    
    public final void addInference(Inference arg) {

        if (arg != null) {
            if (inference == null) {
                inference = new LinkedHashSet();
            }
            inference.add(arg);
        }

    }
    
    public final void removeInference(Inference arg) {

        if (inference != null && arg != null) {
            inference.remove(arg);
        }

    }
    
    public final Set getContent() {

        if (content == null) {
            return java.util.Collections.EMPTY_SET;
        }
        return java.util.Collections.unmodifiableSet(content);
    }
    
    public final void addContent(MoveContent arg) {

        if (arg != null) {
            if (content == null) {
                content = new LinkedHashSet();
            }
            content.add(arg);
        }

    }
    
    public final void removeContent(MoveContent arg) {

        if (content != null && arg != null) {
            content.remove(arg);
        }

    }
    
    public CommitmentStore() {

    }
    
    public Set inference;
    
    public Set content;

}
