
/*
 * @(#)Inference.java
 *
 * Generated by <a href="http://lci.cs.ubbcluj.ro/ocle/>OCLE 2.0</a>
 * using <a href="http://jakarta.apache.org/velocity/">
 * Velocity Template Engine 1.3rc1</a>
 */

/**
 *
 * @author unascribed
 */
public class Inference extends MoveContent {

    
    public MoveContent getData() {

        return null;

    }
    
    public Proposition getConclusion() {

        return null;

    }
    
    public Inference() {

    }
    
    private MoveContent data;
    
    private Proposition consequence;

}
