
/*
 * @(#)Move.java
 *
 * Generated by <a href="http://lci.cs.ubbcluj.ro/ocle/>OCLE 2.0</a>
 * using <a href="http://jakarta.apache.org/velocity/">
 * Velocity Template Engine 1.3rc1</a>
 */

/**
 *
 * @author unascribed
 */
public class Move {

    
    public String getType() {

        return null;

    }
    
    public final Turn getTurn() {

        return turn;
    }
    
    public final void setTurn(Turn arg) {

        if (turn != arg) {
            Turn temp = turn;
            turn = null;//to avoid infinite recursions
            if (temp != null) {
                temp.removeMove(this);
            }
            if (arg != null) {
                turn = arg;
                arg.addMove(this);
            }
        }

    }
    
    public final MoveContent getContent() {

        return content;
    }
    
    public final void setContent(MoveContent arg) {

        content = arg;
    }
    
    public Move() {

    }
    
    public Turn turn;
    
    public MoveContent content;
    
    private String type;

}
