
/*
 * @(#)Proposition.java
 *
 * Generated by <a href="http://lci.cs.ubbcluj.ro/ocle/>OCLE 2.0</a>
 * using <a href="http://jakarta.apache.org/velocity/">
 * Velocity Template Engine 1.3rc1</a>
 */

/**
 *
 * @author unascribed
 */
public class Proposition extends MoveContent {

    
    public Proposition() {

    }

}
